### ISSUE TITLE
question: Why does the current implementation require two arrays to be inputed rather than a single object with alias, version key:value pairs?

### ISSUE THREAD

**Issue by benhinchley** [newscorpaus/semver-alias#1]
I noticed that the current implementation requires a user to pass in two arrays one with the version numbers, and the other with the aliases for those versions numbers
```javascript
getAlias = semverAlias(
    ['5.0.0', '4.0.0', '0.10.38'],
    ['Optimus Prime', 'Bumblebee', 'Megatron']
);
```
I was wondering why it was implemented like that, compared to say having the user pass in an object with the version to alias mappings in it like so
```javascript
getAlias = semverAlias({
    'Optimus Prime' : '0.10.38',
    'Bumblebee' : '4.0.0',
    'Megatron' : '5.0.0'
});
```

**Comment by indieisaconcept** [comment]
@benhinchley thanks for the question - it was intentional.

Internally semver-alias constructs a similar object and provides two-way aliasing between a version and an alias. I did not want to tightly couple a version to an alias since the list of data used to derive an alias may be less than the versions requiring to be aliased.

Also you do not need to manually setup the mapping - semver-alias does this for you automatically.

We are using this module to alias the version of node.js we use so that we can expose that version public for diagnosing running servers. I could have manually constructed an initial object but opted for a more automated approach.

**Comment by benhinchley** [comment]
Thanks for the response @indieisaconcept , makes a lot of sense :+1:
